export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_LAYOUT = 'COLLAPSE_LAYOUT';
export const HEADER_BACK_COLOR = 'HEADER_BACK_COLOR';
export const COLLAPSE_TAB_MENU = 'COLLAPSE_TAB_MENU';
export const COLLAPSE_HEADER_MENU = 'COLLAPSE_HEADER_MENU';